<?php
/**
 * Implements hook_node_info()
 */
function product_node_info() {
    return array(
        'product' => array(
            'name' => t('Product'),
            'base' => 'product',
            'description' => t('You can define new Products here'),
            'has_title' => TRUE,
            'title_label' => t('Product title')
         )
    );
}
/**
 * Implements hook_menu()
 */
function product_menu() {
  $items['list-product-data'] = array(
    'title' => t('Your Projects'),
    'description' => 'Your Sleetmute FPA Projects',
    'page callback' => 'prodcuts_list',
    'access arguments' => array('access content'),
    // 'type' => MENU_NORMAL_ITEM,
	  'access callback' => TRUE,
      // 'type' => MENU_NORMAL_ITEM
  );
  return $items;
  }
  
  function prodcuts_list() {
  $header = array(
    array(
      'data' => t('Nid'),
      'field' => 'nid'
    ),
    array(
      'data' => t('Title'),
      'field' => 'title'
    ),
    array(
      'data' => t('Status'),
      'field' => 'status'
    ),
    array(
      'data' => t('Product Price Value'),
      'field' => 'product_price_value'
    ),
    array(
      'data' => t('Created'),
      'field' => 'created'
    ),
    array(
      'data' => t('Updated'),
      'field' => 'changed'
    ),
  );
  
  
  $data = array();
  
  # set the database table
  $res = db_select('node', 'n')
          ->condition('type', 'product')
          ->extend('PagerDefault')->extend('TableSort') ->orderByHeader($header)
          ->fields('n', array('nid','title','status','created','changed',))
          ->limit(10)->execute()->fetchAll();
  //echo"<pre>";print_r($res);exit;

  
/*  $nodes = node_load_multiple($nids); */
 
  # execute the query
  /* $results = $query->execute();*/

  foreach ($res as $key => $value) {
  $nid = $value->nid;
  $node = node_load($nid);
  
  $data[]= array(
      $value->nid,
      $value->title,
      $value->status,
      $node->product_price[LANGUAGE_NONE][0]['value'],
      'created' => format_date($value->created, 'custom', 'd-m-Y'),
      'changed' => format_date($value->changed, 'custom', 'd-m-Y'),
    );
  }
 
  $output = theme('table', array('header' => $header, 'rows' => $data));
 
  $output .= theme('pager');
  return $output;

}
/**
 * Implement hook_form()
 */
function product_form($node, $form_state) {
    return node_content_form($node, $form_state);
}

